models/VideoArchive.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "video_archive".
 *
 * @property integer $id
 * @property integer $drive_id
 * @property string $create_date
 * @property integer $worked_organization
 * @property string $worked_place
 * @property string $worked_vehicle_number
 * @property string $time_lapse
 * @property string $drive_destroy_date
 * @property string $drive_destroy_employer
 *
 * @property Organization $workedOrganization
 */
class VideoArchive extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'video_archive';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['drive_id', 'create_date', 'worked_organization', 'worked_place', 'time_lapse','worked_vehicle_number'], 'required'],
            [['drive_id', 'worked_organization'], 'integer'],
            [[ 'time_lapse', 'createDateLocale','destroyDateLocale'], 'safe'],
            [['createDateLocale','destroyDateLocale'], 'date', 'format' => 'php:d.m.Y'],
            [['create_date', 'drive_destroy_date'], 'date', 'format' => 'php:Y-m-d'],
            [['worked_place', 'drive_destroy_employer', 'worked_vehicle_number'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'drive_id' => 'Порядковый номер диска',
            'create_date' => 'Дата поступления',
            'worked_organization' => 'Подрядная организация',
            'worked_place' => 'Место работ',
            'worked_vehicle_number' => 'Гос. номер авто',
            'time_lapse' => 'Длительность',
            'drive_destroy_date' => 'Дата уничтожения диска',
            'drive_destroy_employer' => 'Сотрудник',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWorkedOrganization()
    {
        return $this->hasOne(Organization::className(), ['id' => 'worked_organization']);
    }

    public function getCreateDateLocale() { return $this->getDateLocaleAttribute('create_date'); }
    public function setCreateDateLocale($value) { $this->setDateLocaleAttribute('create_date', $value);}

    public function getDestroyDateLocale() { return $this->getDateLocaleAttribute('drive_destroy_date');}
    public function setDestroyDateLocale($value) { $this->setDateLocaleAttribute('drive_destroy_date', $value); }

    private function getDateLocaleAttribute($attributeName) {
        $return = "";
        if (!empty($this->$attributeName)) {
            try {
                $return = \Yii::$app->formatter->asDate($this->$attributeName, 'php:d.m.Y');
            } catch (\Yii\base\InvalidParamException $e) {
                //return "";// \Yii::$app->formatter->asDate($this->getOldAttribute($attributeName), 'php:d.m.Y');
            }
        }

        return $return;
    }
    private function setDateLocaleAttribute($attributeName,  $value) {
        $this->$attributeName = $this->convertDateToLocale($value);
    }
    protected function convertDateToLocale($value) {
        if ( preg_match("/(\d{2}).(\d{2}).(\d{4})/", $value )) {
            $dt = \DateTime::createFromFormat("d.m.Y", $value);
            if ($dt !== false) {
                return $dt->format("Y-m-d");
            }
        } else
        {
            return $value;
        }
    }
    
    public function destroyDrive() {
        $this->drive_destroy_date = (new \DateTime())->format('Y-m-d');
        if (!Yii::$app->user->isGuest)
            $this->drive_destroy_employer = Yii::$app->user->identity->username;
        return $this->save();
    }
}

controllers/VideoArchiveController.php
<?php

namespace app\controllers;

use app\models\VideoArchiveSearch;
use yii\filters\AccessControl;
use Yii;
use app\models\VideoArchive;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \mPDF;
/**
 * VideoArchiveController implements the CRUD actions for VideoArchive model.
 */
class VideoArchiveController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all VideoArchive models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new VideoArchiveSearch();

        $dataProvider = $searchModel->search(Yii::$app->request->get());

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    /**
     * Displays a single VideoArchive model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new VideoArchive model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new VideoArchive();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing VideoArchive model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing VideoArchive model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    
    public function actionDestroy($id) {
        $this->findModel($id)->destroyDrive();
        return $this->redirect(['index']);
    }
    
    public function actionReport() {
        //print_r("sdaads");
        $searchModel = new VideoArchiveSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->get());

        $this->layout = '//print';
        
       // $mpdf=new mPDF('utf-8', 'A4-L');
        //$mpdf->WriteHTML('<p>Hallo World</p>');
       // echo $mpdf->Output();
       // exit;
        Yii::$app->response->format = 'pdf';
        Yii::$container->set(Yii::$app->response->formatters['pdf']['class'], ['format' => 'A4-L']);        
        return $this->render('report', ['data'=>$dataProvider->getModels()]);
     
     
    }
    /**
     * Finds the VideoArchive model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return VideoArchive the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = VideoArchive::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/video-archive/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\VideoArchive */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="video-archive-form">

    <?php

    $this->registerJsFile('@web/js/bootstrap-datetimepicker.min.js', ['position' => \yii\web\View::POS_END, 'depends'=>[yii\web\JqueryAsset::className()]]);
    $this->registerJsFile('@web/js/bootstrap-slider.js', ['position' => \yii\web\View::POS_END, 'depends'=>[yii\web\JqueryAsset::className()]]);
    $this->registerJsFile('@web/js/VideoArchiveForm.js', ['position' => \yii\web\View::POS_END, 'depends'=>[yii\web\JqueryAsset::className()]]);
    $this->registerCssFile('@web/css/bootstrap-datetimepicker.min.css');
    $this->registerCssFile('@web/css/bootstrap-slider.css');


    $form = ActiveForm::begin(); ?>
    <script>
        
    </script>
    <?= $form->field($model, 'drive_id')->textInput() ?>

    <?= $form->field($model, 'createDateLocale')->textInput([]) ?>


    <?= $form->field($model, 'worked_organization')->dropDownList(
        yii\helpers\ArrayHelper::map(\app\models\Organization::find()->all(), 'id', 'title'), ['prompt'=>'Select please']) ?>

    <?= $form->field($model, 'worked_vehicle_number')->textInput() ?>

    <?= $form->field($model, 'worked_place')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'time_lapse')->textInput() ?><div id="time_lapse_picker"></div>

    <?= $form->field($model, 'destroyDateLocale')->textInput() ?>



    <?= $form->field($model, 'drive_destroy_employer')->textInput(['maxlength' => 255]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/video-archive/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\VideoArchive */

$this->title = 'Create Video Archive';
$this->params['breadcrumbs'][] = ['label' => 'Video Archives', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="video-archive-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/video-archive/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Video Archives';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="video-archive-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Video Archive', ['create'], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Create PDF Report', ['report'], ['class' => 'btn btn-info', 'id'=> 'GenReport']) ?>
    </p>

    <?php
        $this->registerJsFile('@web/js/VideoArchiveGrid.js', ['position'=>\yii\web\View::POS_END, 'depends'=>[yii\web\JqueryAsset::className()]]);
        $this->registerJS("
            $('input[name=\"VideoArchiveSearch[drive_destroy_date]\"]').datetimepicker({minView:2, format: 'dd.mm.yyyy', todayHighlight: true});
            $('input[name=\"VideoArchiveSearch[create_date]\"]').datetimepicker({minView:2, format: 'dd.mm.yyyy', todayHighlight: true});",
            \yii\web\View::POS_END);

    echo GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
          //  'id',
            'drive_id',
            ['attribute' => 'create_date', 'format' => ['date', "d.M.Y"]],
            ['attribute' => 'title', 'value' => 'workedOrganization.title'],
            'worked_place',
            'worked_vehicle_number',
            ['attribute' => 'drive_destroy_date', 'format' => ['date', "d.M.Y"]],
            'drive_destroy_employer',
            'time_lapse',
        //    ['class' => 'yii\grid\ActionColumn'],
            [
                'class' => \yii\grid\ActionColumn::className(),
                'buttons'=>[
                    'delete' => function($url, $model, $key) {
                        return Html::a('<span class="glyphicon glyphicon-remove" title="Удалить"></span>', $url,
                            ['data-method'=>"post", 'data-confirm' => 'Are you sure?']);
                    },
                    'destroy'=>function ($url, $model, $key) {
                    return $model->drive_destroy_date === null ? Html::a('<span class="glyphicon glyphicon-trash" title="Уничтожить"></span>', 
                        Yii::$app->getUrlManager()->createUrl(['video-archive/destroy','id'=>$model['id']])) : '';
                }],
                'template'=>'{view}{update}{delete}{destroy}',
                'options' => ['width' => '80px']
            ]
        ],

    ]); ?>

</div>

views/video-archive/report.php
<?php /** @var $data app\models\VideoArchive[] */ $c = 0;?>
<style type="text/css">
    thead td {
        text-align: center;
    }
    table {
        border-collapse: collapse;
    }
    td {
        border: 1px solid black;
    }
</style>
<h2 align="center">Форма журнала учета видеоинформации</h2>
<table>
    <thead><tr>
        <td>№ п/п</td>
        <td>Порядковый номер диска</td>
        <td>Дата поступления</td>
        <td>Наименование подрядной организации/подразделения, от которого поступила видеоинформация</td>
        <td>Место проведения работ (наименование, километр МТ)</td>
        <td>Государственный регистрационный знак, марка (модель) экскаватора/бульдозера</td>
        <td>Временной интервал записанной видеоинформации</td>
        <td>Подпись отствественного за введение архива</td>
        <td>Дата уничтожения диска</td>
        <td>Инициалы, подпись лица, уничтожевшего диск</td>
    </tr><tr class="col_num" >
        <?php for($i=0; $i<10;$i++) { echo "<td>".($i+1)."</td>"; } ?>
    </tr>
    </thead>
    <tbody>
    <?php foreach($data as $d) { $c++;
        ?>
        <tr>
            <td><?= $c ?></td>
            <td><?= $d->drive_id ?></td>
            <td><?= ( new DateTime($d->create_date))->format("d.m.Y") ?></td>
            <td><?= $d->workedOrganization->title ?></td>
            <td><?= $d->worked_place ?></td>
            <td><?= $d->worked_vehicle_number ?></td>
            <td><?= $d->time_lapse ?></td>
            <td></td>
            <td><?= isset($d->drive_destroy_date)?( new DateTime($d->drive_destroy_date))->format("d.m.Y"):"" ?></td>
            <td><?= $d->drive_destroy_employer ?></td>
        </tr>
    <?php } ?>
    <?= str_repeat("<tr>".str_repeat("<td>&nbsp;</td>",10)."</tr>", 28-count($data)); ?>


    </tbody>
</table>

views/video-archive/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\VideoArchive */

$this->title = 'Update Video Archive: ' . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Video Archives', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="video-archive-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/video-archive/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\VideoArchive */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Video Archives', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="video-archive-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'drive_id',
            ['attribute' => 'create_date', 'format' => ['date', "d.M.Y"]],
            'worked_organization',
            'worked_vehicle_number',
            'worked_place',
            'time_lapse',
            ['attribute' => 'drive_destroy_date', 'format' => ['date', "d.M.Y"]],
            'drive_destroy_employer',
        ],
    ]) ?>

</div>